version: "3.7"
services:
  mongo:
    image: mongo:5.0.6
    restart: always
    secrets:
      - mongo-user
      - mongo-pass
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo-user
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo-pass
    volumes:
      - db-mongo:/data/db
  redis:
    image: redis:7.0

  hakke_deploy:
    image: ddosakura/hakke:0.2.0
    secrets:
      - mongo-user
      - mongo-pass
    volumes:
      - type: bind
        source: d:/devenv/hakke_deploy
        target: /storage
    depends_on:
      - mongo
      - redis
    tty: true
    entrypoint: ["bash"]
volumes:
  db-mongo:
secrets:
  mongo-user:
    file: secrets/mongo-user
  mongo-pass:
    file: secrets/mongo-pass
